### register

# POST http://localhost:8000/api/v1/auth/register/
# Content-Type: application/json

# {
#     "email": "amirhusseinghasemian@outlook.com",
#     "password": "amiroutlook123456",
#     "first_name": "Amir hussein",
#     "last_name": "Ghasemian"
# }



# POST http://localhost:8000/api/v1/auth/token/refresh/
# Content-Type: application/json

# {
#     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4ODQyNzc3NSwiaWF0IjoxNzg3ODIyOTc1LCJqdGkiOiJlZTBmYWY5NmIxYjQ0YzBjYTEzNTEwNDBjMDgzMWM3NCIsInVzZXJfaWQiOiJlOThiNDgyMy1iZTIxLTQzNGQtODhmNi1kODQzODc3NjZjNGEifQ.R06wwGAfssL9ORDmqIWMPIfx-3HTbUAwGfWIsNfLE4Q"
# }


# POST http://localhost:8000/api/v1/auth/token/refresh/
# Content-Type: application/json

# {
#     "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4ODQyNzc3NSwiaWF0IjoxNzg3ODIyOTc1LCJqdGkiOiJlZTBmYWY5NmIxYjQ0YzBjYTEzNTEwNDBjMDgzMWM3NCIsInVzZXJfaWQiOiJlOThiNDgyMy1iZTIxLTQzNGQtODhmNi1kODQzODc3NjZjNGEifQ.R06wwGAfssL9ORDmqIWMPIfx-3HTbUAwGfWIsNfLE4Q"
# }


POST http://localhost:8000/api/v1/auth/email/verify/
Content-Type: application/json

{
    "token": "oGc87TzeehxfovIvXt_HijsskUXFu5tF3_2QK4rNyKs"
}
